### ISSUE TITLE
Use $XDG_DATA_HOME

### ISSUE THREAD

**Issue by Scotsguy** [frapa/timers#1]
According to https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html, the .timers directory (on Linux) should be at `$XDG_DATA_HOME/timers` or `$HOME/.local/share/timers` if not set.

~~However, instead of finding this manually (and across all operating systems), consider https://crates.io/crates/dirs or https://crates.io/crates/directories~~

Instead of doing `dirs::home_dir().push(".timers")`, consider `dirs::data_dir().push("timers")`
(Or some other, less "generic" name, maybe)

**Comment by frapa** [comment]
Hi Scotsguy,

Thanks for the suggestion. I'll look into the crates you mentioned and see if I can change it.

**Comment by frapa** [comment]
@Scotsguy I fixed this with 9cf73b5453b793ad573700c3e628f614dc16182d. I also added temporarily some code to automatically migrate the folder.
